# -*- coding: utf-8 -*-
"""API BCRA - Estadisticas cambiarias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbZlJZ3hH2XxyAt1ATTqm2-aH98izsb1
"""

import requests
from requests.packages import urllib3
import json
import pandas as pd

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

maestro_divisas = requests.get("https://api.bcra.gob.ar/estadisticascambiarias/v1.0/Maestros/Divisas", verify=False)

#print(maestro_divisas.json())
json_maestro_divisas = pd.json_normalize(maestro_divisas.json()["results"])
print(json_maestro_divisas.head())

cotizaciones_fecha = {"fecha": "2025-05-23"}

cotizaciones = requests.get("https://api.bcra.gob.ar//estadisticascambiarias/v1.0/Cotizaciones", verify=False, params=cotizaciones_fecha)

json_cotizaciones=pd.json_normalize(cotizaciones.json()["results"]["detalle"])
print(json_cotizaciones.head())



cotizaciones_fecha = {"fechaDesde": "2025-05-13",
                      "fechaHasta": "2025-05-23"}

cotizacion_brl = requests.get("https://api.bcra.gob.ar//estadisticascambiarias/v1.0/Cotizaciones/BRL", verify=False, params=cotizaciones_fecha)

df_json_completo = pd.DataFrame()

for fecha_cotizacion in cotizacion_brl.json()["results"]:
  json_cotizaciones=pd.json_normalize(fecha_cotizacion["detalle"])
  json_cotizaciones["fecha"] = fecha_cotizacion["fecha"]
  df_json_completo = pd.concat([df_json_completo, json_cotizaciones])

print(df_json_completo)