# -*- coding: utf-8 -*-
"""API BCRA - Estadisticas monetarias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8eWWlBwbKf-Pg8oiRkdr30LmsoOpVmF
"""

import requests
from requests.packages import urllib3
import json
import pandas as pd

def json_bonito(json_feo):
  return(json.dumps(json_feo, indent=4))

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

maestro_monetarias = requests.get("https://api.bcra.gob.ar/estadisticas/v3.0/Monetarias", verify=False)

print(json_bonito(maestro_monetarias.json()))



def json_bonito(json_feo):
  return(json.dumps(json_feo, indent=4))

monetarias_param = {"desde": "2025-01-01",
                    "hasta": "2025-05-21"}

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

maestro_monetarias = requests.get("https://api.bcra.gob.ar/estadisticas/v3.0/Monetarias/1", verify=False, params=monetarias_param)

print(json_bonito(maestro_monetarias.json()))

df_reservas = pd.json_normalize(maestro_monetarias.json()["results"])
print(df_reservas)